Add Note entity and Elementable behaviour
teachbase/amorail pull request #29
Opened 2017-07-20 21:44 UTC by ivanovaleksey

2017-07-20 22:08 UTC, ivanovaleksey commented
But it is said [here](https://developers.amocrm.ru/rest_api/notes_list.php) under **Response Field Guide** section
> element_type | Тип привязанного элемента: 1 - контакт, 2 - сделка, 3 - компания, 4 - задача (результат задачи)

Is seems line note can be placed to task 🤔

2017-07-21 07:36 UTC, palkan requested changes

2017-07-21 07:36 UTC, palkan commented on lib/amorail/entities/elementable.rb
> +    ELEMENT_TYPES = [
Why not just:

```ruby
ELEMENT_TYPES = {
  'contact' => 1,
   ...
}
```

Then we can use it in validation and avoid duplication:

```ruby
validates :element_type, inclusion: ELEMENT_TYPES.values
```

2017-07-21 08:10 UTC, ivanovaleksey commented on lib/amorail/entities/elementable.rb
> +    ELEMENT_TYPES = [
To be honest I just copy-pasted existent solution in constant.
If the structure doesn't matter I totally agree with you.

2017-07-21 08:19 UTC, palkan commented on lib/amorail/entities/elementable.rb
> +    ELEMENT_TYPES = [
Got it. That was a bad decision, let's make it right!

2017-07-21 08:24 UTC, ivanovaleksey commented
@palkan what about my comment above? Having common `Elementable` behaviour seems very delicious, but if Note really can have `element_type = 4 (задача (результат задачи))` it seems to break everything 😞

2017-07-21 09:12 UTC, palkan commented
We can extract validation to specific classes, and use smth like`ELEMENT_TYPES.reject { |k, v| k == 'task' }.values` for Task.

2017-07-21 10:28 UTC, ivanovaleksey commented
@palkan I have pushed the updates. Please check it once again.
By the way I have used symbols, I think it doesn't matter here since we use constant only to generate methods.

2017-07-21 10:32 UTC, palkan approved these changes

2017-07-21 10:32 UTC, merged