[Resolves #48] implement token store & move to oAuth
teachbase/amorail pull request #49
Opened 2021-04-02 13:04 UTC by lHydra

#48 

Делал по аналогии [jwt_sessions#token-store](https://github.com/tuwukee/jwt_sessions#token-store)

Добавил поддержку `token_store` с двумя доступными адаптерами `:memory` и `:redis` куда будут сохраняться `access_token` и `refresh_token` с последующим обновлением.

2021-05-07 05:31 UTC, lHydra commented
@palkan Привет! Сможешь глянуть или кого-нибудь тагнуть, чтоб посмотрел?

2021-05-07 14:04 UTC, palkan commented
Привет!

Давай попробуем @AlexanderShvaykin пингануть)

2021-05-08 08:47 UTC, AlexanderShvaykin requested changes
> Давай попробуем @AlexanderShvaykin пингануть)

Попробуйте) Я гем первый раз вижу, PR прочитал, есть комментарии.

2021-05-08 08:47 UTC, AlexanderShvaykin commented on lib/amorail.rb
> +  extend self
`module_function || class << slef` ?

2021-05-08 08:47 UTC, AlexanderShvaykin commented on lib/amorail/client.rb
> +      @_access = AccessToken.create(
А зачем тут инстанс переменная?

2021-05-08 08:47 UTC, AlexanderShvaykin commented on spec/access_token_spec.rb
> +      expect(access_token.token).to eq('upd_token')
не понятно, что тут проверяется, ну во всяком случае, не сходится с описанием, как тут проверяется, что в сторе токен изменился?

2021-05-08 08:47 UTC, AlexanderShvaykin commented on spec/store_adapters/memory_store_adapter_spec.rb
> +      end
что-то не не очень к persist_access относится, тут скорей fetch_access проверяем.

2021-05-08 08:47 UTC, AlexanderShvaykin commented on spec/store_adapters/memory_store_adapter_spec.rb
> +      expect(store.fetch_access('secret')).to eq({ token: 'upd_token', refresh_token: 'upd_refresh', expiration: upd_expiration })
может тут проверить что значение поменялось?

```ruby
subject { store.update_access('secret', 'upd_token', 'upd_refresh', upd_expiration) }

it ... do
  expect { subject }.to change { store.fetch_access('secret') }.from(...).to(...)
end
```

2021-05-08 08:47 UTC, AlexanderShvaykin commented on lib/amorail/client.rb
> +      refresh_token! if access.expired?
Не увидел в тестах этой проверки, нужно бы написать тест, где будет видно, что запросы с токеном уходят и что он запрашивается если его нет и обновляется если он просрочен.

2021-05-08 08:48 UTC, AlexanderShvaykin commented on README.md
> +    redis_db_name: 0
Редис кажется избыточным, я бы написал доку как можно добавлять сторы самому, чтобы клиент сам конфигурировал как ему нужно.

2021-05-08 09:51 UTC, AlexanderShvaykin commented
Чеки падают, я в мастере поправил это, перевел в actions.

2021-05-21 12:34 UTC, lHydra commented on lib/amorail.rb
> +  extend self
По этому пункту не совсем понял

2021-05-21 12:38 UTC, lHydra commented on README.md
> +    redis_db_name: 0
Просто внедряя в приложение, точно понадобится где-то кроме памяти хранить токены, а редис считай прям из коробки можно брать и использовать

2021-05-21 13:51 UTC, lHydra commented on README.md
> +    redis_db_name: 0
@AlexanderShvaykin просто когда добавляешь в приложение, в любом случае понадобится где-то сохранять ключи "надолго", а тут будет сразу из коробки вариант с редисом. Может его оставить + добавить доку?

2021-05-31 16:05 UTC, AlexanderShvaykin approved these changes

2021-05-31 16:05 UTC, AlexanderShvaykin commented on README.md
> +    redis_db_name: 0
хорошо

2021-05-31 16:07 UTC, merged